# Generated by Django 5.1.4 on 2024-12-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('GQ', 'Gender Queer'), ('GF', 'Gender Fluid'), ('O', 'Other')], default='O', max_length=2)),
                ('dob', models.DateField(null=True)),
                ('name_oec', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('virtual', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('support_letter', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('medium', models.CharField(max_length=300)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
