# Generated by Django 5.1.4 on 2025-01-15 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('GQ', 'Gender Queer'), ('GF', 'Gender Fluid'), ('O', 'Other')], default='O', max_length=2)),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('name_oec', models.CharField(max_length=150, verbose_name='Name of organization/educational institute/community')),
                ('role', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('virtual', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Attending Virtually')),
                ('support_letter', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('medium', models.CharField(max_length=300)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
