# Generated by Django 5.1.4 on 2025-01-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='medium',
            field=models.CharField(choices=[('R', 'Referral'), ('OI', 'Organization/Institution'), ('E', 'Email Advertisement'), ('S', 'Social Media'), ('O', 'Other')], default='O', max_length=2),
        ),
    ]
