# Generated by Django 5.1.4 on 2025-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_attendee_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='country_residence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country of Residence'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Role/Title'),
        ),
    ]
