# Generated by Django 5.1.4 on 2025-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_attendee_country_residence_alter_attendee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='country_residence',
            field=models.CharField(max_length=100, verbose_name='Country of Residence'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='linkedin',
            field=models.URLField(),
        ),
    ]
