# Generated by Django 5.1.4 on 2025-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_attendee_country_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='paid',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Nationality'),
        ),
    ]
