# Generated by Django 5.1.4 on 2025-01-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_attendee_paid_alter_attendee_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='accepted',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
